### ISSUE TITLE
Icons don't work on mobile (iPhone)

### ISSUE THREAD

**Issue by jis3r** [imfenghuang/icons#1]

**Comment by imfenghuang** [comment]
get it. let me fix it.

**Comment by imfenghuang** [comment]
hi @jis3r , the icon `div` use `mouseenter` and `mouseleave` mouse event, however in iOS safari, the mouse event can't be triggered if the element is not a clickable element. So i set `role='button' tableindex='0'` to the `div` to make it act as a clickable element.(i tryed only set `role='button'`, it didn't work).

doc: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html

**Comment by jis3r** [comment]
Sounds good! I had a similar issue with my icons in the beginning, but interestingly, Svelte handles mouseenter as a klick somehow when on mobile. Maybe there is something similar for Vue? I just tested and SearchIcon for example works on mobile, because the animation gets only triggered initially on mouseenter and then plays. LayersIcon or FrameIcon however don't work as they have a persisting change when hovered (at least thats my guess)

**Comment by imfenghuang** [comment]
hi @jis3r let me add some additional information

![image](https://github.com/user-attachments/assets/a6b2534b-bc43-422c-905e-fdf20e835508)
![image](https://github.com/user-attachments/assets/0cd2774b-0073-48ad-b0da-2a71036278d9)

in react, `onMouseEnter` is dependent on `mouseout` and `mouseover`, and `mouseout` and `mouseover` can be triggered on a `div` element in iOS safari (test iOS 16.5.1) which is delegated to the root node , so it's performance is ok.


![image](https://github.com/user-attachments/assets/b2745a62-6fdc-451a-813b-de9d9390c98b)

in vue, the event is listened on itself by `patchEvent` (`@mouseenter` is that the element listen the `mouseenter` itself), and the `mouseenter` can't be triggered on the unclickable element in iOS safari, so in the beginning, `icons` did't work on iPhone.

I'm not sure about Svelte‘s event handling, but I guess the framework handles it.

**Comment by jis3r** [comment]
Very interesting, thank you! The icons also seem to work now :)

**Comment by imfenghuang** [comment]
> Very interesting, thank you! The icons also seem to work now :)

yeah, because I add the `role` and `tabindex` attributes that make the `div` element as a clickable element in iOS safari, then it can be triggered with `mouseenter` and `mouseleave` event.
